### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by Jens1503** [adafruit/Adafruit_CircuitPython_MAX31865#10]
Hi! I am using this library on a raspberry pi 3B+ and it works great, except when I try do longer measurements, then I get the error below. The temperature from two sensors and the time are stored in a .txt file. The issue does not seem to come from a lack of space on the raspberry (still got 4.7 Gb free space). The two last times it happened the measurement stopped after 1 hour (.txt file of 80 Kb) and around 2 hours. Any ideas? 

Thanks a lot,
Jens  

> Traceback (most recent call last):
  File "pt100_2_sensors.py", line 25, in <module>
    file_temp_time.write("{0} {1} {2}\n".format(time.time(), sensor_1.temperature, sensor_2.temperature))
  File "/usr/local/lib/python3.5/dist-packages/adafruit_max31865.py", line 238, in temperature
    raw_reading = self.resistance
  File "/usr/local/lib/python3.5/dist-packages/adafruit_max31865.py", line 223, in resistance
    resistance = self.read_rtd()
  File "/usr/local/lib/python3.5/dist-packages/adafruit_max31865.py", line 213, in read_rtd
    self._write_u8(_MAX31865_CONFIG_REG, config)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_max31865.py", line 138, in _write_u8
    device.write(self._BUFFER, end=2)
  File "/usr/local/lib/python3.5/dist-packages/busio.py", line 129, in write
    return self._spi.write(buf, start, end)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/spi.py", line 39, in write
    self._spi.open(self._port, 0)
OSError: [Errno 12] Cannot allocate memory

**Comment by caternuson** [comment]
Can you post the full code listing for the most simple example that shows this issue.

**Comment by caternuson** [comment]
Thanks. Nothing obviously wrong there.

Do you know if it's always failing at the same line? In the stack trace you posted, it's failing here:
```python
file_temp_time.write("{0} {1} {2}\n".format(time.time(), sensor_1.temperature, sensor_2.temperature))
```
In general, it's acting like there's a communication issue between the Pi and the sensor. It could be a wiring issue, something marginal that only happens infrequently. Unfortunately, can't tell if it's 1 or 2 given it's failing on a line that calls both.

Try changing your forever loop to this:
```python
while True:
        temperature_1 = sensor_1.temperature
        resistance_1 = sensor_1.resistance
        temperature_2 = sensor_2.temperature
        resistance_2 = sensor_2.resistance
	print('Temperature Sensor 1: {0:0.3f}C'.format(temperature_1))
	print('Resistance Sonsor 1: {0:0.3f} Ohms'.format(sensor_1.resistance))
	print('Temperature Sensor 2: {0:0.3f}C'.format(temperature_2))
	print('Resistance Sensor 2: {0:0.3f} Ohms'.format(sensor_2.resistance))
	file_temp_time.write("{0} {1} {2}\n".format(time.time(), temperature_1, temperature_2))
	file_temp_time.flush()
	time.sleep(2)
```
and see if it fails consistently on the same line. That may help indicate it's specific to one sensor.

**Comment by Jens1503** [comment]
Thanks! I'll update the code and see if it fails the same place or if it is random. However, I have soldered the cinnections, so I think the connections should be alright. Never know, though.

**Comment by kattni** [comment]
@Jens1503 Are you still running into this?

**Comment by dherrada** [comment]
Closing due to inactivity
