### ISSUE TITLE
OSError: [Errno 24] Too many open files: '/proc/cpuinfo'

### ISSUE THREAD

**Issue by upracht** [adafruit/Adafruit_CircuitPython_MAX31865#27]
Continuous reading of the module MAX31865 with a PT100 temperature sensors in an infinite loop crashes after a constant number of iterations with the error 

_OSError: [Errno 24] Too many open files: '/proc/cpuinfo'_

Reading before the error occures works fine using the adafruit-supplied python code. The while==True loop does not contain any file opening process. For one module the error occures after 1019 loops, for 5 modules after 203. The max number of open files allowed is (ulimit -n) 1024. The errror only occurs for the system depicted below. For RasPi zero + stretch the essentially identical python code works without problems.

**System:** 
- Adafruit MAX31865 PT100-board
- Raspberry Pi 4 Model B Rev 1.4 (8GB)
- Linux fourB 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux (Raspbian Buster 10)
- Python 3.7.3

**Relevant package versions:**
- Adafruit-ADS1x15==1.0.2
- Adafruit-Blinka==6.4.1
- adafruit-circuitpython-busdevice==5.0.6
- adafruit-circuitpython-max31865==2.2.8
- Adafruit-GPIO==1.0.4
- Adafruit-PlatformDetect==3.4.0
- Adafruit-PureIO==1.1.8
- adafruit-python-shell==1.3.1

**Code:**
PT100.py

```
import board
import busio
import digitalio
import time
import adafruit_max31865

def read_PT100():
        spi = busio.SPI(board.SCK,MOSI=board.MOSI,MISO=board.MISO)
        cs = digitalio.DigitalInOut(board.D26)
        sensor = adafruit_max31865.MAX31865(spi,cs,rtd_nominal=100.0, ref_resistor=430.0, wires=4)
        T = sensor.temperature
        return T
```

test.py:
```
from PT100 import read_PT100
i = 0
while True:
      print(f"{i}   {read_PT100()}")
      i += 1
```

**Full error:**
Traceback (most recent call last):
  File "test.py", line 4, in <module>
  File "/home/<user>/Programme/LT_Testbench/PT100.py", line 31, in read_PT100
  File "/home/<user>/.local/lib/python3.7/site-packages/adafruit_max31865.py", line 98, in __init__
  File "/home/<user>/.local/lib/python3.7/site-packages/adafruit_max31865.py", line 120, in _read_u8
  File "/home/<user>/.local/lib/python3.7/site-packages/adafruit_bus_device/spi_device.py", line 76, in __enter__
  File "/usr/local/lib/python3.7/dist-packages/busio.py", line 198, in configure
  File "/home/<user>/.local/lib/python3.7/site-packages/adafruit_platformdetect/board.py", line 426, in any_raspberry_pi
  File "/home/<user>/.local/lib/python3.7/site-packages/adafruit_platformdetect/board.py", line 198, in _pi_rev_code
  File "/home/<user>/.local/lib/python3.7/site-packages/adafruit_platformdetect/__init__.py", line 49, in get_cpuinfo_field
OSError: [Errno 24] Too many open files: '/proc/cpuinfo'

**Comment by FoamyGuy** [comment]
I'm not sure about the specific error you are seeing. But I think more generally it might be better to initialize your SPI bus, pins, and sensor once before your loop begins, and then take readings from it within the main loop.

Right now this code seems to be re-initializing all of those things every iteration through the main loop. This would take extra time and could lead to other trouble I believe.

**Comment by upracht** [comment]
I don´t know why, but moving the SPI init outside the loop solved the problem. Thanks!
