### ISSUE TITLE
Installing the module fresh on a RPi3 / RPi Zero breaks, due to evolving dependencies

### ISSUE THREAD

**Issue by Gui13** [adafruit/Adafruit_CircuitPython_MAX31865#29]
Hello,

I've been struggling to make the code work for my RPi 3/ Zero with a fresh install, and I just figured the problem:

Adafruit_CircuitPython_MAX31865 depends on Adafruit_Blinka, which has evolved a great deal since you release these examples.

And either the code in Blinka of Platform Detect has regressed or something, but this is what I have right now:

Using the test.py files as below:

```python
import time
import board
import busio
import digitalio
import adafruit_max31865

spi = busio.SPI(board.SCLK, MOSI=board.MOSI, MISO=board.MISO) # GPIO 11, 10 and 9 on Rpi
cs = digitalio.DigitalInOut(board.CE0)  # CE0 is D8 on Rpi
sensor = adafruit_max31865.MAX31865(spi, cs, wires=4)

while True:
    temp = sensor.temperature
    print("Temperature: {0:0.3f}C".format(temp))
    time.sleep(1.0)
```

We start on a fresh virtualenv named `latest`:

```bash
pi@rpi(rw):~$ source latest/bin/activate
pi@rpi(rw):~$ pip3 install Adafruit_CircuitPython_MAX31865
[...]
Successfully installed Adafruit-Blinka-5.13.1 Adafruit-CircuitPython-MAX31865-2.2.8 Adafruit-PlatformDetect-2.28.0 Adafruit-PureIO-1.1.8 RPi.GPIO-0.7.0 adafruit-circuitpython-busdevice-5.0.6 aenum-3.0.0 pyftdi-0.52.9 pyserial-3.5 pyusb-1.1.1 rpi-ws281x-4.2.6 sysv-ipc-1.0.1
pythonpi@rpi(rw):~$ python3 test.py
Temperature: -241.553C
Temperature: -241.553C
Temperature: -241.553C
^CTraceback (most recent call last):
  File "test.py", line 15, in <module>
    time.sleep(1.0)
KeyboardInterrupt
pi@rpi(rw):~$ pip3 list
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Package                          Version
-------------------------------- -------
Adafruit-Blinka                  5.13.1
adafruit-circuitpython-busdevice 5.0.6
adafruit-circuitpython-max31865  2.2.8
Adafruit-PlatformDetect          2.28.0
Adafruit-PureIO                  1.1.8
aenum                            3.0.0
pip                              20.3.4
pkg-resources                    0.0.0
pyftdi                           0.52.9
pyserial                         3.5
pyusb                            1.1.1
rpi-ws281x                       4.2.6
RPi.GPIO                         0.7.0
setuptools                       50.3.2
sysv-ipc                         1.0.1
wheel                            0.36.2

```

If I switch to another fresh virtualenv named `works`:

```bash
pi@rpi(rw):~$ source works/bin/activate
pi@rpi(rw):~$ pip3 install Adafruit-Blinka==2.4.* adafruit-circuitpython-max31865 Adafruit-PlatformDetect==1.* --upgrade
[...]
Successfully installed Adafruit-Blinka-2.4.1 Adafruit-PlatformDetect-1.4.5 Adafruit-PureIO-1.1.8 RPi.GPIO-0.7.0 adafruit-circuitpython-busdevice-5.0.6 adafruit-circuitpython-max31865-2.2.8 rpi-ws281x-4.2.6 spidev-3.5 sysv-ipc-1.0.1
pi@rpi(rw):~$ python3 test.py
Temperature: 20.292C
Temperature: 20.258C
Temperature: 20.292C
^CTraceback (most recent call last):
  File "test.py", line 15, in <module>
    time.sleep(1.0)
KeyboardInterrupt
pi@rpi(rw):~$ pip3 list
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Package                          Version
-------------------------------- -------
Adafruit-Blinka                  2.4.1
adafruit-circuitpython-busdevice 5.0.6
adafruit-circuitpython-max31865  2.2.8
Adafruit-PlatformDetect          1.4.5
Adafruit-PureIO                  1.1.8
pip                              20.3.4
pkg-resources                    0.0.0
rpi-ws281x                       4.2.6
RPi.GPIO                         0.7.0
setuptools                       50.3.2
spidev                           3.5
sysv-ipc                         1.0.1
wheel                            0.36.2
```

So you see, using recent versions of Blinka breaks the code, the RTD returns temparatures of -241°C.
If I switch to a (older) working version of Blinka and PlatformDetect, all is fine.

Did I write my code badly? (This is directly sourced from your example..)

Or did Blinka/Platform Detect break something in their code?

**Comment by makermelissa** [comment]
Are you experiencing this on the latest version of Blinka? We are currently at 6.4.2 and you are running 5.13.1. Also, which version of Raspberry Pi OS are you running? I'm guessing you are running an older version of Raspbian (perhaps stretch) that has Python 3.5, so it's not installing the latest version. Since I don't have the hardware on hand, so I wanted to start out by verifying, but I'll try the latest version of Blinka once I get it.

**Comment by Gui13** [comment]
I confirm that I'm on an older Debian (Stretch), and I'm stuck with Py3.5! You got the right idea, although I suppose you might be supporting this version?
Anyways, clearly something doesn't work between Blinka 5.13.1 and PlatformDetect 2.28.0.

I could help debug this if needed.

**Comment by makermelissa** [comment]
I just tested on the latest version of Blinka and it runs fine.

**Comment by makermelissa** [comment]
I'm closing for now since we are currently only maintaining a single version of Blinka. This might be a bigger issue in that we should maybe consider supporting a couple of different versions of Blinka like we do with CircuitPython.
